#!/usr/bin/env bash
# zecnode-mount-setup.sh
# Find the large data drive (>400GB) that grandma wants to use for Zcash
# DOES NOT mount, unmount, or change any system configuration
# ONLY identifies which mounted filesystem to use for data storage
#
# Version: 1.3.14
# Created by: CyberAxe (www.dontpanic.biz)
#
# Run on Mint:  sudo bash ./zecnode-mount-setup.sh

set -euo pipefail

info()  { echo -e "\e[36m[*]\e[0m $*"; }
ok()    { echo -e "\e[32m[✓]\e[0m $*"; }
warn()  { echo -e "\e[33m[!]\e[0m $*"; }
err()   { echo -e "\e[31m[✗]\e[0m $*"; exit 1; }

[[ "${EUID:-$(id -u)}" -eq 0 ]] || err "Run with sudo."

echo
info "=== Zcash Data Storage Selection ==="
info "Finding large drives (over 400GB) already mounted..."
echo

# ============================================================================
# 1. List mounted filesystems over 400GB
# ============================================================================
MOUNTS=()
IDX=1

# Get mounted filesystems, exclude tmpfs/sysfs/pseudo filesystems
while IFS= read -r mount_line; do
  DEVICE=$(echo "$mount_line" | awk '{print $1}')
  MOUNT_PT=$(echo "$mount_line" | awk '{print $NF}')
  SIZE_KB=$(df "$MOUNT_PT" 2>/dev/null | tail -1 | awk '{print $2}')
  
  if [[ -n "$SIZE_KB" && "$SIZE_KB" -gt 0 ]]; then
    SIZE_GB=$((SIZE_KB / 1024 / 1024))
    
    # Only show drives over 400GB
    if [[ $SIZE_GB -ge 400 ]]; then
      AVAIL_KB=$(df "$MOUNT_PT" 2>/dev/null | tail -1 | awk '{print $4}')
      AVAIL_GB=$((AVAIL_KB / 1024 / 1024))
      
      MOUNTS+=("$MOUNT_PT")
      printf "  [%d] %-25s  %4dGB total, %4dGB available\n" "$IDX" "$MOUNT_PT" "$SIZE_GB" "$AVAIL_GB"
      IDX=$((IDX + 1))
    fi
  fi
done < <(df -P | grep -v "Filesystem\|tmpfs\|sysfs\|devtmpfs")

if [[ ${#MOUNTS[@]} -eq 0 ]]; then
  warn "WARNING: No mounted drives over 400GB found!"
  warn "Zcash blockchain sync requires ~400GB minimum (recommended 500GB+)"
  warn "Attempting with smaller drive will likely FAIL during sync."
  echo
  read -rp "Do you want to continue anyway with a smaller drive? (y/N): " CONTINUE_SMALL
  
  if [[ ! "$CONTINUE_SMALL" =~ ^[Yy]$ ]]; then
    err "Installation cancelled. Please add a larger drive and try again."
  fi
  
  warn "Proceeding with smaller drive - sync may fail!"
  echo
  
  # Fall back to ANY mounted drive over 50GB minimum
  IDX=1
  while IFS= read -r mount_line; do
    DEVICE=$(echo "$mount_line" | awk '{print $1}')
    MOUNT_PT=$(echo "$mount_line" | awk '{print $NF}')
    SIZE_KB=$(df "$MOUNT_PT" 2>/dev/null | tail -1 | awk '{print $2}')
    
    if [[ -n "$SIZE_KB" && "$SIZE_KB" -gt 0 ]]; then
      SIZE_GB=$((SIZE_KB / 1024 / 1024))
      
      # Accept drives over 50GB minimum as fallback
      if [[ $SIZE_GB -ge 50 ]]; then
        AVAIL_KB=$(df "$MOUNT_PT" 2>/dev/null | tail -1 | awk '{print $4}')
        AVAIL_GB=$((AVAIL_KB / 1024 / 1024))
        
        MOUNTS+=("$MOUNT_PT")
        printf "  [%d] %-25s  %4dGB total, %4dGB available (⚠ TOO SMALL)\n" "$IDX" "$MOUNT_PT" "$SIZE_GB" "$AVAIL_GB"
        IDX=$((IDX + 1))
      fi
    fi
  done < <(df -P | grep -v "Filesystem\|tmpfs\|sysfs\|devtmpfs")
  
  if [[ ${#MOUNTS[@]} -eq 0 ]]; then
    err "No mounted drives over 50GB found at all. Cannot proceed."
  fi
fi

echo

# ============================================================================
# 2. Grandma picks which drive to use
# ============================================================================
read -rp "Which drive should we use for Zcash data? Pick [1-${#MOUNTS[@]}]: " CHOICE

if ! [[ "$CHOICE" =~ ^[0-9]+$ ]] || [[ $CHOICE -lt 1 ]] || [[ $CHOICE -gt ${#MOUNTS[@]} ]]; then
  err "Invalid choice. Enter a number 1-${#MOUNTS[@]}"
fi

DATA_PATH="${MOUNTS[$((CHOICE - 1))]}"

# Special case: if root filesystem selected, use /var/lib for data
if [[ "$DATA_PATH" == "/" ]]; then
  DATA_PATH="/var/lib"
  info "Using /var/lib for data storage (default system location)"
fi

ok "Selected: $DATA_PATH"
echo

# ============================================================================
# 3. Verify the path is writable
# ============================================================================
info "Verifying write permissions on $DATA_PATH..."

if [[ ! -w "$DATA_PATH" ]]; then
  err "$DATA_PATH is not writable. Check permissions."
fi

ok "Path is writable ✓"
echo

# ============================================================================
# 4. Save choice to environment config file (for other scripts to use)
# ============================================================================
info "Saving data path for use by other scripts..."

ZECNODE_CONFIG="/etc/zecnode/zecnode.conf"
mkdir -p /etc/zecnode

# Create config file with the chosen path
cat > "$ZECNODE_CONFIG" <<EOF
# Zecnode Configuration
# Generated by zecnode-mount-setup.sh
# This file is sourced by all other scripts

# Data storage path (where Zebra and lightwalletd store data)
ZECNODE_DATA_PATH="$DATA_PATH"
EOF

chmod 644 "$ZECNODE_CONFIG"
ok "Configuration saved to: $ZECNODE_CONFIG"
echo

# ============================================================================
# 5. Show summary
# ============================================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ok "STORAGE SELECTION COMPLETE ✓"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo
info "Data storage path: $DATA_PATH"
info "The following will be created:"
info "  $DATA_PATH/zebra         ← Zebra blockchain sync data"
info "  $DATA_PATH/lightwalletd  ← lightwalletd wallet data"
echo
info "No mounts, unmounts, or system changes were made."
info "Your existing drive mounts remain unchanged."
echo

# ============================================================================
# CONFIRMATION PROMPT - AUTO-CHAIN
# ============================================================================
read -p "Ready to proceed? (Y/n default=Y): " MOUNT_OK
MOUNT_OK=${MOUNT_OK:-Y}

if [[ "$MOUNT_OK" =~ ^[Yy]$ ]]; then
  ok "Storage selection confirmed. Starting toolchain setup..."
  echo
  # AUTO-CHAIN: Automatically run the next script
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  exec sudo bash "$SCRIPT_DIR/zecnode-toolchain-setup.sh"
else
  warn "Installation cancelled by user."
  exit 1
fi

